import { BingoOption } from '../models/BingoOption';

const SHARED_CAT_IMAGE = '/assets/cats/orange%20cat.png';

export const SAMPLE_ITEMS: BingoOption[] = [
  { id: 'orange', title: 'Orange', imageSrc: '/assets/cats/orange%20cat.png' },
  { id: 'black', title: 'Black', imageSrc: '/assets/cats/black%20cat.jpg' },
  { id: 'tuxedo', title: 'Tuxedo', imageSrc: '/assets/cats/tuxedo%20cat.png' },
  { id: 'white', title: 'White', imageSrc: '/assets/cats/white%20cat.png' },
  { id: 'tabby', title: 'Tabby', imageSrc: '/assets/cats/tabby%20cat.png' },
  { id: 'tortoise', title: 'Tortoise shell', imageSrc: '/assets/cats/tortoise%20cat.jpg' },
  { id: 'three-legged', title: 'Three-legged', imageSrc: '/assets/cats/three%20legged%20cat.jpg' },
  { id: 'one-eyed', title: 'One-eyed', imageSrc: '/assets/cats/one%20eyed%20cat.jpg' },
  { id: 'no-tail', title: 'No tail', imageSrc: '/assets/cats/cat%20no%20tail.jpg' },
  { id: 'notched-ear', title: 'Notched ear', imageSrc: '/assets/cats/noteched%20ear%20cat.jpg' },
  { id: 'yawning', title: 'Yawning', imageSrc: '/assets/cats/yawning%20cat.jpg' },
  { id: 'sleeping', title: 'Sleeping', imageSrc: '/assets/cats/sleeping%20cat.jpg' },
  { id: 'eating', title: 'Eating', imageSrc: '/assets/cats/cat%20eating.jpg' },
  { id: 'drinking', title: 'Drinking', imageSrc: '/assets/cats/cat%20drinking.jpg' },
  { id: 'under-picnic-table', title: 'Under a picnic table', imageSrc: '/assets/cats/cat%20under%20a%20picnic%20table.jpg' },
  { id: 'on-stone-wall', title: 'On a stone wall', imageSrc: '/assets/cats/cat%20on%20a%20stone%20wall.jpg' },
  { id: 'in-garden', title: 'In a garden', imageSrc: '/assets/cats/in%20a%20garden.jpg' },
  { id: 'near-hydrangeas', title: 'Near Hydrangeas', imageSrc: '/assets/cats/cat%20near%20hydrangeas.jpg' },
  { id: 'under-parked-car', title: 'Under a parked car', imageSrc: SHARED_CAT_IMAGE },
  { id: 'belly-up', title: 'Belly-up', imageSrc: '/assets/cats/cat%20on%20its%20back.jpg' },
  { id: 'fighting', title: 'Fighting', imageSrc: '/assets/cats/cats%20fighting.jpg' },
  { id: 'blue-eyes', title: 'Blue eyes', imageSrc: '/assets/cats/blue%20eyed%20cat.jpg' },
  { id: 'heterochromia', title: 'Two colored eyes', imageSrc: '/assets/cats/cat%20with%20heterochromia.jpg' },
  { id: 'kitten', title: 'Kitten', imageSrc: '/assets/cats/kitten.jpg' },
  { id: 'pregnant', title: 'Pregnant', imageSrc: '/assets/cats/pregnant%20cat.jpg' },
  { id: 'fluffy', title: 'Fluffy', imageSrc: '/assets/cats/fluffy%20cat.jpg' },
  { id: 'fat', title: 'Fat', imageSrc: '/assets/cats/fat%20cat.jpg' },
  { id: 'cat-colony', title: 'Colony (5+)', imageSrc: '/assets/cats/cat%20colony.jpg' },
  { id: 'calico', title: 'Calico', imageSrc: '/assets/cats/calico%20cat.jpg' },
  { id: 'weird-meow', title: 'Weird meow', imageSrc: '/assets/cats/cat%20with%20weird%20meow.jpg' },
  { id: 'voiceless-meow', title: 'Voiceless meow', imageSrc: '/assets/cats/voiceless%20meow.jpg' },
  { id: 'friendly', title: 'Friendly', imageSrc: '/assets/cats/friendly%20cat.jpg' },
  { id: 'scaredy-cat', title: 'Scaredy', imageSrc: '/assets/cats/scaredy%20cat.jpg' },
  { id: 'grooming', title: 'Grooming', imageSrc: '/assets/cats/cat%20grooming.jpg' },
  { id: 'sharing-food', title: 'Sharing food', imageSrc: '/assets/cats/cats%20sharing%20food.jpg' },
  { id: 'collar', title: 'With a collar', imageSrc: '/assets/cats/cat%20with%20a%20collar.jpg' },
  { id: 'outside-cafe', title: 'Outside a cafe', imageSrc: '/assets/cats/cafe%20cat.jpg' },
  { id: 'near-church', title: 'Near a church', imageSrc: '/assets/cats/church%20cat.jpg' },
  { id: 'on-balcony', title: 'On a balcony', imageSrc: '/assets/cats/balcony%20cat.jpg' },
  { id: 'on-roof', title: 'On a roof', imageSrc: '/assets/cats/cat%20on%20a%20roof.jpg' },
  { id: 'in-a-box', title: 'In a box', imageSrc: '/assets/cats/cat%20in%20a%20box.jpg' },
  { id: 'in-a-window', title: 'In a window', imageSrc: '/assets/cats/cat%20in%20a%20window.jpg' },
  { id: 'chasing-tail', title: 'Chasing its tail', imageSrc: SHARED_CAT_IMAGE },
  { id: 'bird-watching', title: 'Watching a bird', imageSrc: SHARED_CAT_IMAGE },
  { id: 'on-a-car', title: 'On a car', imageSrc: SHARED_CAT_IMAGE },
];
