import { BingoOption } from '../models/BingoOption';

const CAT_ASSET_BASE = `${import.meta.env.BASE_URL}assets/cats/`;
const catAsset = (filename: string): string => `${CAT_ASSET_BASE}${filename}`;
const SHARED_CAT_IMAGE = catAsset('orange%20cat.png');

export const SAMPLE_ITEMS: BingoOption[] = [
  { id: 'orange', title: 'Orange', imageSrc: catAsset('orange%20cat.png') },
  { id: 'black', title: 'Black', imageSrc: catAsset('black%20cat.jpg') },
  { id: 'tuxedo', title: 'Tuxedo', imageSrc: catAsset('tuxedo%20cat.png') },
  { id: 'white', title: 'White', imageSrc: catAsset('white%20cat.png') },
  { id: 'tabby', title: 'Tabby', imageSrc: catAsset('tabby%20cat.png') },
  { id: 'tortoise', title: 'Tortoise shell', imageSrc: catAsset('tortoise%20cat.jpg') },
  { id: 'three-legged', title: 'Three-legged', imageSrc: catAsset('three%20legged%20cat.jpg') },
  { id: 'one-eyed', title: 'One-eyed', imageSrc: catAsset('one%20eyed%20cat.jpg') },
  { id: 'no-tail', title: 'No tail', imageSrc: catAsset('cat%20no%20tail.jpg') },
  { id: 'notched-ear', title: 'Notched ear', imageSrc: catAsset('noteched%20ear%20cat.jpg') },
  { id: 'yawning', title: 'Yawning', imageSrc: catAsset('yawning%20cat.jpg') },
  { id: 'sleeping', title: 'Sleeping', imageSrc: catAsset('sleeping%20cat.jpg') },
  { id: 'eating', title: 'Eating', imageSrc: catAsset('cat%20eating.jpg') },
  { id: 'drinking', title: 'Drinking', imageSrc: catAsset('cat%20drinking.jpg') },
  { id: 'under-picnic-table', title: 'Under a picnic table', imageSrc: catAsset('cat%20under%20a%20picnic%20table.jpg') },
  { id: 'on-stone-wall', title: 'On a stone wall', imageSrc: catAsset('cat%20on%20a%20stone%20wall.jpg') },
  { id: 'in-garden', title: 'In a garden', imageSrc: catAsset('in%20a%20garden.jpg') },
  { id: 'near-hydrangeas', title: 'Near Hydrangeas', imageSrc: catAsset('cat%20near%20hydrangeas.jpg') },
  { id: 'under-parked-car', title: 'Under a parked car', imageSrc: catAsset('cat%20under%20car.png') },
  { id: 'belly-up', title: 'Belly-up', imageSrc: catAsset('cat%20on%20its%20back.jpg') },
  { id: 'fighting', title: 'Fighting', imageSrc: catAsset('cats%20fighting.jpg') },
  { id: 'blue-eyes', title: 'Blue eyes', imageSrc: catAsset('blue%20eyed%20cat.jpg') },
  { id: 'heterochromia', title: 'Two colored eyes', imageSrc: catAsset('cat%20with%20heterochromia.jpg') },
  { id: 'kitten', title: 'Kitten', imageSrc: catAsset('kitten.jpg') },
  { id: 'pregnant', title: 'Pregnant', imageSrc: catAsset('pregnant%20cat.jpg') },
  { id: 'fluffy', title: 'Fluffy', imageSrc: catAsset('fluffy%20cat.jpg') },
  { id: 'fat', title: 'Fat', imageSrc: catAsset('fat%20cat.jpg') },
  { id: 'cat-colony', title: 'Colony (5+)', imageSrc: catAsset('cat%20colony.jpg') },
  { id: 'calico', title: 'Calico', imageSrc: catAsset('calico%20cat.jpg') },
  { id: 'weird-meow', title: 'Weird meow', imageSrc: catAsset('cat%20with%20weird%20meow.jpg') },
  { id: 'voiceless-meow', title: 'Voiceless meow', imageSrc: catAsset('voiceless%20meow.jpg') },
  { id: 'friendly', title: 'Friendly', imageSrc: catAsset('friendly%20cat.jpg') },
  { id: 'scaredy-cat', title: 'Scaredy', imageSrc: catAsset('scaredy%20cat.jpg') },
  { id: 'grooming', title: 'Grooming', imageSrc: catAsset('cat%20grooming.jpg') },
  { id: 'sharing-food', title: 'Sharing food', imageSrc: catAsset('cats%20sharing%20food.jpg') },
  { id: 'collar', title: 'With a collar', imageSrc: catAsset('cat%20with%20a%20collar.jpg') },
  { id: 'outside-cafe', title: 'Outside a cafe', imageSrc: catAsset('cafe%20cat.jpg') },
  { id: 'near-church', title: 'Near a church', imageSrc: catAsset('church%20cat.jpg') },
  { id: 'on-balcony', title: 'On a balcony', imageSrc: catAsset('balcony%20cat.jpg') },
  { id: 'on-roof', title: 'On a roof', imageSrc: catAsset('cat%20on%20a%20roof.jpg') },
  { id: 'in-a-box', title: 'In a box', imageSrc: catAsset('cat%20in%20a%20box.jpg') },
  { id: 'in-a-window', title: 'In a window', imageSrc: catAsset('cat%20in%20a%20window.jpg') },
  { id: 'chasing-tail', title: 'Chasing its tail', imageSrc: SHARED_CAT_IMAGE },
  { id: 'bird-watching', title: 'Watching a bird', imageSrc: SHARED_CAT_IMAGE },
  { id: 'on-a-car', title: 'On a car', imageSrc: catAsset('cat%20on%20a%20car.png') },
];
